-- ADMINS TABLE
CREATE TABLE IF NOT EXISTS Admins (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Email TEXT UNIQUE NOT NULL,
    PasswordHash TEXT NOT NULL
);


-- STAFF TABLE
CREATE TABLE IF NOT EXISTS Staff (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    FullName TEXT NOT NULL,
    Email TEXT UNIQUE NOT NULL,
    PasswordHash TEXT NOT NULL
);


-- MEMBERS TABLE
CREATE TABLE IF NOT EXISTS Members (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    Email TEXT UNIQUE NOT NULL,
    Phone TEXT,
    PasswordHash TEXT NOT NULL,
    JoinDate TEXT NOT NULL
);


-- MEMBERSHIP PLANS
CREATE TABLE IF NOT EXISTS MembershipPlans (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    PlanName TEXT NOT NULL,
    Price REAL NOT NULL,
    DurationMonths INTEGER NOT NULL
);


-- MEMBERSHIPS
CREATE TABLE IF NOT EXISTS Memberships (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    MemberId INTEGER NOT NULL,
    PlanId INTEGER NOT NULL,
    StartDate TEXT NOT NULL,
    EndDate TEXT NOT NULL,
    FOREIGN KEY (MemberId) REFERENCES Members(Id),
    FOREIGN KEY (PlanId) REFERENCES MembershipPlans(Id)
);


-- PAYMENTS
CREATE TABLE IF NOT EXISTS Payments (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    MemberId INTEGER NOT NULL,
    Amount REAL NOT NULL,
    PaymentDate TEXT NOT NULL,
    FOREIGN KEY (MemberId) REFERENCES Members(Id)
);